<?php
/**
 * @file
 * wamex_currency_taxonomy_fields.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function wamex_currency_taxonomy_fields_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_currency_code'
  $field_bases['field_currency_code'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_currency_code',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 3,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_exchange_rate'
  $field_bases['field_exchange_rate'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_exchange_rate',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  return $field_bases;
}
